version: '3'
services:

  load-generator:
    image: alpine/bombardier@sha256:3647592d94c654898d0327ca5080f6d9cf98e3ecdc407c3249ba78e270761a9a
    networks:
      - lbdmesh
    entrypoint: /bin/ash
    command: -c 'sleep 120 ; bombardier -c 1000 -d 1h http://load-balancer:8080/'

  nginx:
    build:
      context: ./nginx
      args:
        download_key: ${download_key}
        agent_key: ${agent_key}
        nginx_version: '1.17.2'
    networks:
      lbdmesh:
        aliases:
          - load-balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/instana-config.json:/etc/instana-config.json
    expose:
      - "8080"

  server-app-1:
    image: server-app
    networks:
      lbdmesh:
        aliases:
          - server-app-1
    environment:  
      # - INSTANA_DEV=1
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=server-app-1
      - MEMORY_ALLOCATED_PER_REQUEST=50KB # Accepts the java.time.Duration#parse format, see https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-
      - MEMORY_ALLOCATED_MAXIMUM=280MB # Accepts the java.time.Duration#parse format, see https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-
    expose:
      - "8080"

  server-app-2:
    image: server-app
    networks:
      lbdmesh:
        aliases:
          - server-app-2
    environment:  
      # - INSTANA_DEV=1
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=server-app-2
      - MEMORY_ALLOCATED_PER_REQUEST=5KB # Accepts the java.time.Duration#parse format, see https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-
      - MEMORY_ALLOCATED_MAXIMUM=280MB # Accepts the java.time.Duration#parse format, see https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-
    expose:
      - "8080"

  agent:
    image: containers.instana.io/instana/release/agent/static:latest
    pid: host
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
      - ./agent/configuration-demo.yaml:/opt/instana/agent/etc/instana/configuration-demo.yaml
      # - ./agent/com.instana.agent.main.sender.File.cfg:/opt/instana/agent/etc/instana/com.instana.agent.main.sender.File.cfg # Log spans received by the agent to a file in /opt/instana/agent/data/log
    networks:
      lbdmesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=${agent_endpoint:-saas-us-west-2.instana.io}
      - INSTANA_AGENT_ENDPOINT_PORT=${agent_endpoint_port:-443}
      - INSTANA_DOWNLOAD_KEY=${download_key}
      - INSTANA_AGENT_KEY=${agent_key}
      - INSTANA_AGENT_ZONE=${agent_zone:-load-balancer-demo}
    expose:
      - "42699"

networks:
  lbdmesh: {}
